#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Nearest.Droid.Resource", IsApplication=true)]

namespace Nearest.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Nearest.Droid.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int androidcolors = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int bg = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int blue = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int darkblue = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int darkgreen = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int darkorange = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int darkpurple = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int darkred = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int green = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int orange = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int purple = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int red = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int textblack = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textgray = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int green = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int yellow = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int ButtonNorth = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int ButtonSouth = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int LayoutDowntown = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int LayoutUptown = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int TextDestSouth = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int TextTimeSouth = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int TextViewDestNorth = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int TextViewTagline = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int TextViewTimeNorth = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int TextViewTitle = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int tagline = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int title = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
