/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

	public static class SettingsKeys
	{

		#region Visible Settings


		public const string VersionNumber = "VersionNumberString";

		public const string BuildNumber = "BuildNumber";

		public const string GitCommitHash = "GitCommitHash";

		public const string UseInternetServices = "UseInternetServices";

		public const string ShowAllStations = "ShowAllStations";

		public const string UomTime = "UomTime";

		public const string UomTimeThreshold = "UomTimeThreshold";

		public const string UomDistance = "UomDistance";

		public const string UomDistanceThreshold = "UomDistanceThreshold";


		#endregion


		#region Hidden Settings


		public const string NotApplicable = "NotApplicable";


		#endregion
	}
}